name: PHP CS Fixer PR

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  php-cs-fixer-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - uses: php-actions/composer@v2

      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run
